// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-concat-stream/099a88b57dcc9968246e8b1b3651e914a1a2c324/index.d.ts
declare module 'concat-stream' {
  import { Writable } from 'stream';

  class ConcatStream extends Writable {}

  namespace ConcatStream {
    export interface Options {
      // Supports "string", "buffer", "array", "uint8array" or "object".
      encoding?: string;
    }
  }

  const concatStream: {
    (cb: (data: any) => any): ConcatStream;
    (opts: ConcatStream.Options, cb: (data: any) => any): ConcatStream;

    new (cb: (data: any) => any): ConcatStream;
    new (opts: ConcatStream.Options, cb: (data: any) => any): ConcatStream;
  };

  export = concatStream;
}
